inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
  Max: 30

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'