# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/user_settings', type: :request do
  # UserSetting. As you add validations to UserSetting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      UserSetting.create! valid_attributes
      get user_settings_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      user_setting = UserSetting.create! valid_attributes
      get user_setting_url(user_setting)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_user_setting_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      user_setting = UserSetting.create! valid_attributes
      get edit_user_setting_url(user_setting)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new UserSetting' do
        expect do
          post user_settings_url, params: { user_setting: valid_attributes }
        end.to change(UserSetting, :count).by(1)
      end

      it 'redirects to the created user_setting' do
        post user_settings_url, params: { user_setting: valid_attributes }
        expect(response).to redirect_to(user_setting_url(UserSetting.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new UserSetting' do
        expect do
          post user_settings_url, params: { user_setting: invalid_attributes }
        end.to change(UserSetting, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_settings_url, params: { user_setting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested user_setting' do
        user_setting = UserSetting.create! valid_attributes
        patch user_setting_url(user_setting), params: { user_setting: new_attributes }
        user_setting.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the user_setting' do
        user_setting = UserSetting.create! valid_attributes
        patch user_setting_url(user_setting), params: { user_setting: new_attributes }
        user_setting.reload
        expect(response).to redirect_to(user_setting_url(user_setting))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user_setting = UserSetting.create! valid_attributes
        patch user_setting_url(user_setting), params: { user_setting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested user_setting' do
      user_setting = UserSetting.create! valid_attributes
      expect do
        delete user_setting_url(user_setting)
      end.to change(UserSetting, :count).by(-1)
    end

    it 'redirects to the user_settings list' do
      user_setting = UserSetting.create! valid_attributes
      delete user_setting_url(user_setting)
      expect(response).to redirect_to(user_settings_url)
    end
  end
end
